#!/bin/bash
# 4. Write a script which monitors the modifications made to the /etc/crontab
# file and sends an e-mail to root if the file is modified. Create a
# scheduled task to run this script everyday at midnight.

TARGET=/etc/crontab
DUMP=/etc/.crontab_dump
CURRENT_HASH=`md5sum $TARGET | awk '{ print $1 }'`
NEW_HASH=`md5sum $DUMP | awk '{ print $1 }'`

if [ ! -e $DUMP ]; then
	echo "Dump does not exist"
	sudo cp $TARGET $DUMP
	exit 0
fi

if [ -z "$CURRENT_HASH" ] | [ -z "$NEW_HASH" ]; then
	echo "CURRENT_HASH is empty."
else
	if [ "$CURRENT_HASH" != "$NEW_HASH" ]; then
		echo "crontab has been updated" | mail -s "changes:" root
	fi
fi
sudo cp $TARGET $DUMP
